# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ingestion.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fingestion.proto\x12\x0cingestion.v1\"P\n\x17TriggerIngestionRequest\x12\x13\n\x0btotal_books\x18\x01 \x01(\x05\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\"`\n\x18TriggerIngestionResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x13\n\x0btotal_books\x18\x03 \x01(\x05\x12\x0f\n\x07message\x18\x04 \x01(\t\"+\n\x19GetIngestionStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"\xbb\x01\n\x1aGetIngestionStatusResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x11\n\tprocessed\x18\x03 \x01(\x05\x12\r\n\x05total\x18\x04 \x01(\x05\x12\x12\n\nsuccessful\x18\x05 \x01(\x05\x12\x0e\n\x06\x66\x61iled\x18\x06 \x01(\x05\x12\r\n\x05\x65rror\x18\x07 \x01(\t\x12\x12\n\nstarted_at\x18\x08 \x01(\x03\x12\x14\n\x0c\x63ompleted_at\x18\t \x01(\x03\"(\n\x16\x43\x61ncelIngestionRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\";\n\x17\x43\x61ncelIngestionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xbe\x02\n\x10IngestionService\x12\x61\n\x10TriggerIngestion\x12%.ingestion.v1.TriggerIngestionRequest\x1a&.ingestion.v1.TriggerIngestionResponse\x12g\n\x12GetIngestionStatus\x12\'.ingestion.v1.GetIngestionStatusRequest\x1a(.ingestion.v1.GetIngestionStatusResponse\x12^\n\x0f\x43\x61ncelIngestion\x12$.ingestion.v1.CancelIngestionRequest\x1a%.ingestion.v1.CancelIngestionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ingestion_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRIGGERINGESTIONREQUEST']._serialized_start=33
  _globals['_TRIGGERINGESTIONREQUEST']._serialized_end=113
  _globals['_TRIGGERINGESTIONRESPONSE']._serialized_start=115
  _globals['_TRIGGERINGESTIONRESPONSE']._serialized_end=211
  _globals['_GETINGESTIONSTATUSREQUEST']._serialized_start=213
  _globals['_GETINGESTIONSTATUSREQUEST']._serialized_end=256
  _globals['_GETINGESTIONSTATUSRESPONSE']._serialized_start=259
  _globals['_GETINGESTIONSTATUSRESPONSE']._serialized_end=446
  _globals['_CANCELINGESTIONREQUEST']._serialized_start=448
  _globals['_CANCELINGESTIONREQUEST']._serialized_end=488
  _globals['_CANCELINGESTIONRESPONSE']._serialized_start=490
  _globals['_CANCELINGESTIONRESPONSE']._serialized_end=549
  _globals['_INGESTIONSERVICE']._serialized_start=552
  _globals['_INGESTIONSERVICE']._serialized_end=870
# @@protoc_insertion_point(module_scope)
