# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ingestion_pb2 as ingestion__pb2


class IngestionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TriggerIngestion = channel.unary_unary(
                '/ingestion.v1.IngestionService/TriggerIngestion',
                request_serializer=ingestion__pb2.TriggerIngestionRequest.SerializeToString,
                response_deserializer=ingestion__pb2.TriggerIngestionResponse.FromString,
                )
        self.GetIngestionStatus = channel.unary_unary(
                '/ingestion.v1.IngestionService/GetIngestionStatus',
                request_serializer=ingestion__pb2.GetIngestionStatusRequest.SerializeToString,
                response_deserializer=ingestion__pb2.GetIngestionStatusResponse.FromString,
                )
        self.CancelIngestion = channel.unary_unary(
                '/ingestion.v1.IngestionService/CancelIngestion',
                request_serializer=ingestion__pb2.CancelIngestionRequest.SerializeToString,
                response_deserializer=ingestion__pb2.CancelIngestionResponse.FromString,
                )


class IngestionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TriggerIngestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIngestionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelIngestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TriggerIngestion': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerIngestion,
                    request_deserializer=ingestion__pb2.TriggerIngestionRequest.FromString,
                    response_serializer=ingestion__pb2.TriggerIngestionResponse.SerializeToString,
            ),
            'GetIngestionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIngestionStatus,
                    request_deserializer=ingestion__pb2.GetIngestionStatusRequest.FromString,
                    response_serializer=ingestion__pb2.GetIngestionStatusResponse.SerializeToString,
            ),
            'CancelIngestion': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelIngestion,
                    request_deserializer=ingestion__pb2.CancelIngestionRequest.FromString,
                    response_serializer=ingestion__pb2.CancelIngestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ingestion.v1.IngestionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IngestionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TriggerIngestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ingestion.v1.IngestionService/TriggerIngestion',
            ingestion__pb2.TriggerIngestionRequest.SerializeToString,
            ingestion__pb2.TriggerIngestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetIngestionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ingestion.v1.IngestionService/GetIngestionStatus',
            ingestion__pb2.GetIngestionStatusRequest.SerializeToString,
            ingestion__pb2.GetIngestionStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelIngestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ingestion.v1.IngestionService/CancelIngestion',
            ingestion__pb2.CancelIngestionRequest.SerializeToString,
            ingestion__pb2.CancelIngestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
