# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import user_data_pb2 as user__data__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in user_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBookshelf = channel.unary_unary(
                '/user_data.v1.UserDataService/GetBookshelf',
                request_serializer=user__data__pb2.GetBookshelfRequest.SerializeToString,
                response_deserializer=user__data__pb2.BookshelfResponse.FromString,
                _registered_method=True)
        self.UpsertBookshelf = channel.unary_unary(
                '/user_data.v1.UserDataService/UpsertBookshelf',
                request_serializer=user__data__pb2.UpsertBookshelfRequest.SerializeToString,
                response_deserializer=user__data__pb2.BookshelfResponse.FromString,
                _registered_method=True)
        self.DeleteBookshelf = channel.unary_unary(
                '/user_data.v1.UserDataService/DeleteBookshelf',
                request_serializer=user__data__pb2.DeleteBookshelfRequest.SerializeToString,
                response_deserializer=user__data__pb2.EmptyResponse.FromString,
                _registered_method=True)
        self.GetUserBookshelves = channel.unary_unary(
                '/user_data.v1.UserDataService/GetUserBookshelves',
                request_serializer=user__data__pb2.GetUserBookshelvesRequest.SerializeToString,
                response_deserializer=user__data__pb2.BookshelvesListResponse.FromString,
                _registered_method=True)
        self.GetPublicBookshelves = channel.unary_unary(
                '/user_data.v1.UserDataService/GetPublicBookshelves',
                request_serializer=user__data__pb2.GetPublicBookshelvesRequest.SerializeToString,
                response_deserializer=user__data__pb2.BookshelvesListResponse.FromString,
                _registered_method=True)
        self.GetRating = channel.unary_unary(
                '/user_data.v1.UserDataService/GetRating',
                request_serializer=user__data__pb2.GetRatingRequest.SerializeToString,
                response_deserializer=user__data__pb2.RatingResponse.FromString,
                _registered_method=True)
        self.UpsertRating = channel.unary_unary(
                '/user_data.v1.UserDataService/UpsertRating',
                request_serializer=user__data__pb2.UpsertRatingRequest.SerializeToString,
                response_deserializer=user__data__pb2.RatingResponse.FromString,
                _registered_method=True)
        self.DeleteRating = channel.unary_unary(
                '/user_data.v1.UserDataService/DeleteRating',
                request_serializer=user__data__pb2.DeleteRatingRequest.SerializeToString,
                response_deserializer=user__data__pb2.EmptyResponse.FromString,
                _registered_method=True)
        self.GetUserRatings = channel.unary_unary(
                '/user_data.v1.UserDataService/GetUserRatings',
                request_serializer=user__data__pb2.GetUserRatingsRequest.SerializeToString,
                response_deserializer=user__data__pb2.RatingsListResponse.FromString,
                _registered_method=True)
        self.ToggleFavourite = channel.unary_unary(
                '/user_data.v1.UserDataService/ToggleFavourite',
                request_serializer=user__data__pb2.ToggleFavouriteRequest.SerializeToString,
                response_deserializer=user__data__pb2.FavouriteResponse.FromString,
                _registered_method=True)
        self.GetUserFavourites = channel.unary_unary(
                '/user_data.v1.UserDataService/GetUserFavourites',
                request_serializer=user__data__pb2.GetUserFavouritesRequest.SerializeToString,
                response_deserializer=user__data__pb2.BookshelvesListResponse.FromString,
                _registered_method=True)
        self.CreateComment = channel.unary_unary(
                '/user_data.v1.UserDataService/CreateComment',
                request_serializer=user__data__pb2.CreateCommentRequest.SerializeToString,
                response_deserializer=user__data__pb2.CommentResponse.FromString,
                _registered_method=True)
        self.UpdateComment = channel.unary_unary(
                '/user_data.v1.UserDataService/UpdateComment',
                request_serializer=user__data__pb2.UpdateCommentRequest.SerializeToString,
                response_deserializer=user__data__pb2.CommentResponse.FromString,
                _registered_method=True)
        self.DeleteComment = channel.unary_unary(
                '/user_data.v1.UserDataService/DeleteComment',
                request_serializer=user__data__pb2.DeleteCommentRequest.SerializeToString,
                response_deserializer=user__data__pb2.EmptyResponse.FromString,
                _registered_method=True)
        self.GetUserComments = channel.unary_unary(
                '/user_data.v1.UserDataService/GetUserComments',
                request_serializer=user__data__pb2.GetUserCommentsRequest.SerializeToString,
                response_deserializer=user__data__pb2.CommentsListResponse.FromString,
                _registered_method=True)
        self.GetBookComments = channel.unary_unary(
                '/user_data.v1.UserDataService/GetBookComments',
                request_serializer=user__data__pb2.GetBookCommentsRequest.SerializeToString,
                response_deserializer=user__data__pb2.BookCommentsResponse.FromString,
                _registered_method=True)
        self.GetUserBookInfo = channel.unary_unary(
                '/user_data.v1.UserDataService/GetUserBookInfo',
                request_serializer=user__data__pb2.GetUserBookInfoRequest.SerializeToString,
                response_deserializer=user__data__pb2.UserBookInfoResponse.FromString,
                _registered_method=True)
        self.GetPublicProfileStats = channel.unary_unary(
                '/user_data.v1.UserDataService/GetPublicProfileStats',
                request_serializer=user__data__pb2.GetPublicProfileStatsRequest.SerializeToString,
                response_deserializer=user__data__pb2.ProfileStatsResponse.FromString,
                _registered_method=True)
        self.DeleteUserData = channel.unary_unary(
                '/user_data.v1.UserDataService/DeleteUserData',
                request_serializer=user__data__pb2.DeleteUserDataRequest.SerializeToString,
                response_deserializer=user__data__pb2.EmptyResponse.FromString,
                _registered_method=True)


class UserDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBookshelf(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertBookshelf(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBookshelf(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserBookshelves(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPublicBookshelves(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserRatings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToggleFavourite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserFavourites(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserComments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBookComments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserBookInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPublicProfileStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUserData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBookshelf': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookshelf,
                    request_deserializer=user__data__pb2.GetBookshelfRequest.FromString,
                    response_serializer=user__data__pb2.BookshelfResponse.SerializeToString,
            ),
            'UpsertBookshelf': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertBookshelf,
                    request_deserializer=user__data__pb2.UpsertBookshelfRequest.FromString,
                    response_serializer=user__data__pb2.BookshelfResponse.SerializeToString,
            ),
            'DeleteBookshelf': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBookshelf,
                    request_deserializer=user__data__pb2.DeleteBookshelfRequest.FromString,
                    response_serializer=user__data__pb2.EmptyResponse.SerializeToString,
            ),
            'GetUserBookshelves': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserBookshelves,
                    request_deserializer=user__data__pb2.GetUserBookshelvesRequest.FromString,
                    response_serializer=user__data__pb2.BookshelvesListResponse.SerializeToString,
            ),
            'GetPublicBookshelves': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublicBookshelves,
                    request_deserializer=user__data__pb2.GetPublicBookshelvesRequest.FromString,
                    response_serializer=user__data__pb2.BookshelvesListResponse.SerializeToString,
            ),
            'GetRating': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRating,
                    request_deserializer=user__data__pb2.GetRatingRequest.FromString,
                    response_serializer=user__data__pb2.RatingResponse.SerializeToString,
            ),
            'UpsertRating': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertRating,
                    request_deserializer=user__data__pb2.UpsertRatingRequest.FromString,
                    response_serializer=user__data__pb2.RatingResponse.SerializeToString,
            ),
            'DeleteRating': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRating,
                    request_deserializer=user__data__pb2.DeleteRatingRequest.FromString,
                    response_serializer=user__data__pb2.EmptyResponse.SerializeToString,
            ),
            'GetUserRatings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserRatings,
                    request_deserializer=user__data__pb2.GetUserRatingsRequest.FromString,
                    response_serializer=user__data__pb2.RatingsListResponse.SerializeToString,
            ),
            'ToggleFavourite': grpc.unary_unary_rpc_method_handler(
                    servicer.ToggleFavourite,
                    request_deserializer=user__data__pb2.ToggleFavouriteRequest.FromString,
                    response_serializer=user__data__pb2.FavouriteResponse.SerializeToString,
            ),
            'GetUserFavourites': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserFavourites,
                    request_deserializer=user__data__pb2.GetUserFavouritesRequest.FromString,
                    response_serializer=user__data__pb2.BookshelvesListResponse.SerializeToString,
            ),
            'CreateComment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateComment,
                    request_deserializer=user__data__pb2.CreateCommentRequest.FromString,
                    response_serializer=user__data__pb2.CommentResponse.SerializeToString,
            ),
            'UpdateComment': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateComment,
                    request_deserializer=user__data__pb2.UpdateCommentRequest.FromString,
                    response_serializer=user__data__pb2.CommentResponse.SerializeToString,
            ),
            'DeleteComment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteComment,
                    request_deserializer=user__data__pb2.DeleteCommentRequest.FromString,
                    response_serializer=user__data__pb2.EmptyResponse.SerializeToString,
            ),
            'GetUserComments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserComments,
                    request_deserializer=user__data__pb2.GetUserCommentsRequest.FromString,
                    response_serializer=user__data__pb2.CommentsListResponse.SerializeToString,
            ),
            'GetBookComments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookComments,
                    request_deserializer=user__data__pb2.GetBookCommentsRequest.FromString,
                    response_serializer=user__data__pb2.BookCommentsResponse.SerializeToString,
            ),
            'GetUserBookInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserBookInfo,
                    request_deserializer=user__data__pb2.GetUserBookInfoRequest.FromString,
                    response_serializer=user__data__pb2.UserBookInfoResponse.SerializeToString,
            ),
            'GetPublicProfileStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublicProfileStats,
                    request_deserializer=user__data__pb2.GetPublicProfileStatsRequest.FromString,
                    response_serializer=user__data__pb2.ProfileStatsResponse.SerializeToString,
            ),
            'DeleteUserData': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserData,
                    request_deserializer=user__data__pb2.DeleteUserDataRequest.FromString,
                    response_serializer=user__data__pb2.EmptyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user_data.v1.UserDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('user_data.v1.UserDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBookshelf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_data.v1.UserDataService/GetBookshelf',
            user__data__pb2.GetBookshelfRequest.SerializeToString,
            user__data__pb2.BookshelfResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertBookshelf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_data.v1.UserDataService/UpsertBookshelf',
            user__data__pb2.UpsertBookshelfRequest.SerializeToString,
            user__data__pb2.BookshelfResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBookshelf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_data.v1.UserDataService/DeleteBookshelf',
            user__data__pb2.DeleteBookshelfRequest.SerializeToString,
            user__data__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserBookshelves(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_data.v1.UserDataService/GetUserBookshelves',
            user__data__pb2.GetUserBookshelvesRequest.SerializeToString,
            user__data__pb2.BookshelvesListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPublicBookshelves(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_data.v1.UserDataService/GetPublicBookshelves',
            user__data__pb2.GetPublicBookshelvesRequest.SerializeToString,
            user__data__pb2.BookshelvesListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_data.v1.UserDataService/GetRating',
            user__data__pb2.GetRatingRequest.SerializeToString,
            user__data__pb2.RatingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_data.v1.UserDataService/UpsertRating',
            user__data__pb2.UpsertRatingRequest.SerializeToString,
            user__data__pb2.RatingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_data.v1.UserDataService/DeleteRating',
            user__data__pb2.DeleteRatingRequest.SerializeToString,
            user__data__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserRatings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_data.v1.UserDataService/GetUserRatings',
            user__data__pb2.GetUserRatingsRequest.SerializeToString,
            user__data__pb2.RatingsListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ToggleFavourite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_data.v1.UserDataService/ToggleFavourite',
            user__data__pb2.ToggleFavouriteRequest.SerializeToString,
            user__data__pb2.FavouriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserFavourites(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_data.v1.UserDataService/GetUserFavourites',
            user__data__pb2.GetUserFavouritesRequest.SerializeToString,
            user__data__pb2.BookshelvesListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_data.v1.UserDataService/CreateComment',
            user__data__pb2.CreateCommentRequest.SerializeToString,
            user__data__pb2.CommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_data.v1.UserDataService/UpdateComment',
            user__data__pb2.UpdateCommentRequest.SerializeToString,
            user__data__pb2.CommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_data.v1.UserDataService/DeleteComment',
            user__data__pb2.DeleteCommentRequest.SerializeToString,
            user__data__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_data.v1.UserDataService/GetUserComments',
            user__data__pb2.GetUserCommentsRequest.SerializeToString,
            user__data__pb2.CommentsListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBookComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_data.v1.UserDataService/GetBookComments',
            user__data__pb2.GetBookCommentsRequest.SerializeToString,
            user__data__pb2.BookCommentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserBookInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_data.v1.UserDataService/GetUserBookInfo',
            user__data__pb2.GetUserBookInfoRequest.SerializeToString,
            user__data__pb2.UserBookInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPublicProfileStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_data.v1.UserDataService/GetPublicProfileStats',
            user__data__pb2.GetPublicProfileStatsRequest.SerializeToString,
            user__data__pb2.ProfileStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUserData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_data.v1.UserDataService/DeleteUserData',
            user__data__pb2.DeleteUserDataRequest.SerializeToString,
            user__data__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
