from typing import List

from pydantic import BaseModel


class CategoryConfig(BaseModel):
    slug: str
    name: str
    keywords: List[str]
    exact_slugs: List[str] = []


CATEGORIES = {
    "fantasy": CategoryConfig(
        slug="fantasy",
        name="Fantasy",
        keywords=[
            "fantasy",
            "magic",
            "dragons",
            "wizard",
            "witches",
            "mythology",
            "fairies",
            "epic fantasy",
            "high fantasy",
            "urban fantasy",
            "sword and sorcery",
        ],
        exact_slugs=["fantasy", "high-fantasy", "urban-fantasy", "epic-fantasy"],
    ),
    "science-fiction": CategoryConfig(
        slug="science-fiction",
        name="Science Fiction",
        keywords=[
            "science fiction",
            "sci-fi",
            "space",
            "aliens",
            "cyberpunk",
            "dystopian",
            "futuristic",
            "time travel",
            "space opera",
            "post-apocalyptic",
        ],
        exact_slugs=["science-fiction", "sci-fi"],
    ),
    "romance": CategoryConfig(
        slug="romance",
        name="Romance",
        keywords=[
            "romance",
            "love",
            "contemporary romance",
            "historical romance",
            "romantic fantasy",
            "romantasy",
        ],
        exact_slugs=["romance", "love-story"],
    ),
    "mystery-thriller": CategoryConfig(
        slug="mystery-thriller",
        name="Mystery & Thriller",
        keywords=[
            "mystery",
            "thriller",
            "suspense",
            "crime",
            "detective",
            "murder",
            "psychological thriller",
            "true crime",
            "police procedural",
        ],
        exact_slugs=["mystery", "thriller", "crime", "suspense"],
    ),
    "horror": CategoryConfig(
        slug="horror",
        name="Horror",
        keywords=[
            "horror",
            "scary",
            "ghosts",
            "haunted",
            "macabre",
            "supernatural",
            "paranormal",
            "gothic",
        ],
        exact_slugs=["horror", "supernatural-horror"],
    ),
    "historical-fiction": CategoryConfig(
        slug="historical-fiction",
        name="Historical Fiction",
        keywords=[
            "historical fiction",
            "history",
            "world war",
            "tudor",
            "ancient",
            "medieval",
            "regency",
            "victorian",
        ],
        exact_slugs=["historical-fiction", "history"],
    ),
    "young-adult": CategoryConfig(
        slug="young-adult",
        name="Young Adult",
        keywords=[
            "young adult",
            "ya fiction",
            "teen fiction",
            "coming of age",
            "high school",
        ],
        exact_slugs=["young-adult", "ya", "teen"],
    ),
    "classics": CategoryConfig(
        slug="classics",
        name="Classics",
        keywords=[
            "classic",
            "literary fiction",
            "literature",
            "canonical",
            "19th century",
            "20th century literature",
        ],
        exact_slugs=["classics", "classic-literature", "literary-fiction"],
    ),
    "adventure": CategoryConfig(
        slug="adventure",
        name="Adventure",
        keywords=[
            "adventure",
            "action",
            "quest",
            "exploration",
            "survival",
            "treasure hunt",
        ],
        exact_slugs=["adventure", "action-adventure"],
    ),
    "biography": CategoryConfig(
        slug="biography",
        name="Biography & Memoir",
        keywords=[
            "biography",
            "memoir",
            "autobiography",
            "life story",
            "true story",
            "personal narrative",
        ],
        exact_slugs=["biography", "memoir", "autobiography", "biography-memoir"],
    ),
    "self-help": CategoryConfig(
        slug="self-help",
        name="Self-Help",
        keywords=[
            "self-help",
            "personal development",
            "productivity",
            "motivation",
            "self-improvement",
            "mindfulness",
            "habits",
        ],
        exact_slugs=["self-help", "personal-development"],
    ),
    "business": CategoryConfig(
        slug="business",
        name="Business & Economics",
        keywords=[
            "business",
            "economics",
            "entrepreneurship",
            "finance",
            "investing",
            "management",
            "leadership",
            "marketing",
        ],
        exact_slugs=["business", "economics", "finance"],
    ),
    "science-nature": CategoryConfig(
        slug="science-nature",
        name="Science & Nature",
        keywords=[
            "science",
            "physics",
            "biology",
            "chemistry",
            "astronomy",
            "nature",
            "environment",
            "popular science",
            "natural history",
        ],
        exact_slugs=["science", "nature", "popular-science"],
    ),
    "graphic-novels": CategoryConfig(
        slug="graphic-novels",
        name="Graphic Novels & Comics",
        keywords=[
            "graphic novel",
            "comics",
            "manga",
            "illustrated",
            "sequential art",
        ],
        exact_slugs=["graphic-novel", "graphic-novels", "comics", "manga"],
    ),
}
