# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import recommendation_pb2 as recommendation__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in recommendation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecommendationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRecommendationList = channel.unary_unary(
                '/recommendation.v1.RecommendationService/GetRecommendationList',
                request_serializer=recommendation__pb2.GetRecommendationListRequest.SerializeToString,
                response_deserializer=recommendation__pb2.RecommendationListResponse.FromString,
                _registered_method=True)
        self.GetHomePage = channel.unary_unary(
                '/recommendation.v1.RecommendationService/GetHomePage',
                request_serializer=recommendation__pb2.GetHomePageRequest.SerializeToString,
                response_deserializer=recommendation__pb2.HomePageResponse.FromString,
                _registered_method=True)
        self.GetAvailableCategories = channel.unary_unary(
                '/recommendation.v1.RecommendationService/GetAvailableCategories',
                request_serializer=recommendation__pb2.GetAvailableCategoriesRequest.SerializeToString,
                response_deserializer=recommendation__pb2.AvailableCategoriesResponse.FromString,
                _registered_method=True)
        self.RefreshRecommendations = channel.unary_unary(
                '/recommendation.v1.RecommendationService/RefreshRecommendations',
                request_serializer=recommendation__pb2.RefreshRecommendationsRequest.SerializeToString,
                response_deserializer=recommendation__pb2.RefreshRecommendationsResponse.FromString,
                _registered_method=True)
        self.GetBookRecommendations = channel.unary_unary(
                '/recommendation.v1.RecommendationService/GetBookRecommendations',
                request_serializer=recommendation__pb2.GetBookRecommendationsRequest.SerializeToString,
                response_deserializer=recommendation__pb2.BookRecommendationsResponse.FromString,
                _registered_method=True)
        self.GetAuthorRecommendations = channel.unary_unary(
                '/recommendation.v1.RecommendationService/GetAuthorRecommendations',
                request_serializer=recommendation__pb2.GetAuthorRecommendationsRequest.SerializeToString,
                response_deserializer=recommendation__pb2.AuthorRecommendationsResponse.FromString,
                _registered_method=True)


class RecommendationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRecommendationList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHomePage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableCategories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBookRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthorRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRecommendationList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendationList,
                    request_deserializer=recommendation__pb2.GetRecommendationListRequest.FromString,
                    response_serializer=recommendation__pb2.RecommendationListResponse.SerializeToString,
            ),
            'GetHomePage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHomePage,
                    request_deserializer=recommendation__pb2.GetHomePageRequest.FromString,
                    response_serializer=recommendation__pb2.HomePageResponse.SerializeToString,
            ),
            'GetAvailableCategories': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableCategories,
                    request_deserializer=recommendation__pb2.GetAvailableCategoriesRequest.FromString,
                    response_serializer=recommendation__pb2.AvailableCategoriesResponse.SerializeToString,
            ),
            'RefreshRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshRecommendations,
                    request_deserializer=recommendation__pb2.RefreshRecommendationsRequest.FromString,
                    response_serializer=recommendation__pb2.RefreshRecommendationsResponse.SerializeToString,
            ),
            'GetBookRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookRecommendations,
                    request_deserializer=recommendation__pb2.GetBookRecommendationsRequest.FromString,
                    response_serializer=recommendation__pb2.BookRecommendationsResponse.SerializeToString,
            ),
            'GetAuthorRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthorRecommendations,
                    request_deserializer=recommendation__pb2.GetAuthorRecommendationsRequest.FromString,
                    response_serializer=recommendation__pb2.AuthorRecommendationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommendation.v1.RecommendationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommendation.v1.RecommendationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecommendationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRecommendationList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.RecommendationService/GetRecommendationList',
            recommendation__pb2.GetRecommendationListRequest.SerializeToString,
            recommendation__pb2.RecommendationListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHomePage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.RecommendationService/GetHomePage',
            recommendation__pb2.GetHomePageRequest.SerializeToString,
            recommendation__pb2.HomePageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.RecommendationService/GetAvailableCategories',
            recommendation__pb2.GetAvailableCategoriesRequest.SerializeToString,
            recommendation__pb2.AvailableCategoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.RecommendationService/RefreshRecommendations',
            recommendation__pb2.RefreshRecommendationsRequest.SerializeToString,
            recommendation__pb2.RefreshRecommendationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBookRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.RecommendationService/GetBookRecommendations',
            recommendation__pb2.GetBookRecommendationsRequest.SerializeToString,
            recommendation__pb2.BookRecommendationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuthorRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.RecommendationService/GetAuthorRecommendations',
            recommendation__pb2.GetAuthorRecommendationsRequest.SerializeToString,
            recommendation__pb2.AuthorRecommendationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
