# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import books_pb2 as books__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in books_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BooksServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchBooksAndAuthors = channel.unary_unary(
                '/books.v1.BooksService/SearchBooksAndAuthors',
                request_serializer=books__pb2.SearchRequest.SerializeToString,
                response_deserializer=books__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.GetBook = channel.unary_unary(
                '/books.v1.BooksService/GetBook',
                request_serializer=books__pb2.GetBookRequest.SerializeToString,
                response_deserializer=books__pb2.BookDetailResponse.FromString,
                _registered_method=True)
        self.GetAuthor = channel.unary_unary(
                '/books.v1.BooksService/GetAuthor',
                request_serializer=books__pb2.GetAuthorRequest.SerializeToString,
                response_deserializer=books__pb2.AuthorDetailResponse.FromString,
                _registered_method=True)
        self.GetAuthorBooks = channel.unary_unary(
                '/books.v1.BooksService/GetAuthorBooks',
                request_serializer=books__pb2.GetAuthorBooksRequest.SerializeToString,
                response_deserializer=books__pb2.BooksListResponse.FromString,
                _registered_method=True)
        self.GetSeries = channel.unary_unary(
                '/books.v1.BooksService/GetSeries',
                request_serializer=books__pb2.GetSeriesRequest.SerializeToString,
                response_deserializer=books__pb2.SeriesDetailResponse.FromString,
                _registered_method=True)
        self.GetSeriesBooks = channel.unary_unary(
                '/books.v1.BooksService/GetSeriesBooks',
                request_serializer=books__pb2.GetSeriesBooksRequest.SerializeToString,
                response_deserializer=books__pb2.BooksListResponse.FromString,
                _registered_method=True)


class BooksServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchBooksAndAuthors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthorBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeriesBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BooksServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchBooksAndAuthors': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchBooksAndAuthors,
                    request_deserializer=books__pb2.SearchRequest.FromString,
                    response_serializer=books__pb2.SearchResponse.SerializeToString,
            ),
            'GetBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBook,
                    request_deserializer=books__pb2.GetBookRequest.FromString,
                    response_serializer=books__pb2.BookDetailResponse.SerializeToString,
            ),
            'GetAuthor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthor,
                    request_deserializer=books__pb2.GetAuthorRequest.FromString,
                    response_serializer=books__pb2.AuthorDetailResponse.SerializeToString,
            ),
            'GetAuthorBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthorBooks,
                    request_deserializer=books__pb2.GetAuthorBooksRequest.FromString,
                    response_serializer=books__pb2.BooksListResponse.SerializeToString,
            ),
            'GetSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeries,
                    request_deserializer=books__pb2.GetSeriesRequest.FromString,
                    response_serializer=books__pb2.SeriesDetailResponse.SerializeToString,
            ),
            'GetSeriesBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeriesBooks,
                    request_deserializer=books__pb2.GetSeriesBooksRequest.FromString,
                    response_serializer=books__pb2.BooksListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'books.v1.BooksService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('books.v1.BooksService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BooksService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchBooksAndAuthors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books.v1.BooksService/SearchBooksAndAuthors',
            books__pb2.SearchRequest.SerializeToString,
            books__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books.v1.BooksService/GetBook',
            books__pb2.GetBookRequest.SerializeToString,
            books__pb2.BookDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuthor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books.v1.BooksService/GetAuthor',
            books__pb2.GetAuthorRequest.SerializeToString,
            books__pb2.AuthorDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuthorBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books.v1.BooksService/GetAuthorBooks',
            books__pb2.GetAuthorBooksRequest.SerializeToString,
            books__pb2.BooksListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books.v1.BooksService/GetSeries',
            books__pb2.GetSeriesRequest.SerializeToString,
            books__pb2.SeriesDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSeriesBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books.v1.BooksService/GetSeriesBooks',
            books__pb2.GetSeriesBooksRequest.SerializeToString,
            books__pb2.BooksListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
