# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import books_pb2 as books__pb2


class BooksServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchBooksAndAuthors = channel.unary_unary(
                '/books.v1.BooksService/SearchBooksAndAuthors',
                request_serializer=books__pb2.SearchRequest.SerializeToString,
                response_deserializer=books__pb2.SearchResponse.FromString,
                )
        self.GetBook = channel.unary_unary(
                '/books.v1.BooksService/GetBook',
                request_serializer=books__pb2.GetBookRequest.SerializeToString,
                response_deserializer=books__pb2.BookDetailResponse.FromString,
                )
        self.GetAuthor = channel.unary_unary(
                '/books.v1.BooksService/GetAuthor',
                request_serializer=books__pb2.GetAuthorRequest.SerializeToString,
                response_deserializer=books__pb2.AuthorDetailResponse.FromString,
                )
        self.GetAuthorBooks = channel.unary_unary(
                '/books.v1.BooksService/GetAuthorBooks',
                request_serializer=books__pb2.GetAuthorBooksRequest.SerializeToString,
                response_deserializer=books__pb2.BooksListResponse.FromString,
                )


class BooksServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchBooksAndAuthors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthorBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BooksServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchBooksAndAuthors': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchBooksAndAuthors,
                    request_deserializer=books__pb2.SearchRequest.FromString,
                    response_serializer=books__pb2.SearchResponse.SerializeToString,
            ),
            'GetBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBook,
                    request_deserializer=books__pb2.GetBookRequest.FromString,
                    response_serializer=books__pb2.BookDetailResponse.SerializeToString,
            ),
            'GetAuthor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthor,
                    request_deserializer=books__pb2.GetAuthorRequest.FromString,
                    response_serializer=books__pb2.AuthorDetailResponse.SerializeToString,
            ),
            'GetAuthorBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthorBooks,
                    request_deserializer=books__pb2.GetAuthorBooksRequest.FromString,
                    response_serializer=books__pb2.BooksListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'books.v1.BooksService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BooksService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchBooksAndAuthors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books.v1.BooksService/SearchBooksAndAuthors',
            books__pb2.SearchRequest.SerializeToString,
            books__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books.v1.BooksService/GetBook',
            books__pb2.GetBookRequest.SerializeToString,
            books__pb2.BookDetailResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAuthor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books.v1.BooksService/GetAuthor',
            books__pb2.GetAuthorRequest.SerializeToString,
            books__pb2.AuthorDetailResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAuthorBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books.v1.BooksService/GetAuthorBooks',
            books__pb2.GetAuthorBooksRequest.SerializeToString,
            books__pb2.BooksListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
