# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ingestion_pb2 as ingestion__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ingestion_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IngestionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TriggerIngestion = channel.unary_unary(
                '/ingestion.v1.IngestionService/TriggerIngestion',
                request_serializer=ingestion__pb2.TriggerIngestionRequest.SerializeToString,
                response_deserializer=ingestion__pb2.TriggerIngestionResponse.FromString,
                _registered_method=True)
        self.SearchBook = channel.unary_unary(
                '/ingestion.v1.IngestionService/SearchBook',
                request_serializer=ingestion__pb2.SearchBookRequest.SerializeToString,
                response_deserializer=ingestion__pb2.SearchBookResponse.FromString,
                _registered_method=True)
        self.GetDataCoverage = channel.unary_unary(
                '/ingestion.v1.IngestionService/GetDataCoverage',
                request_serializer=ingestion__pb2.GetDataCoverageRequest.SerializeToString,
                response_deserializer=ingestion__pb2.GetDataCoverageResponse.FromString,
                _registered_method=True)
        self.ImportDump = channel.unary_unary(
                '/ingestion.v1.IngestionService/ImportDump',
                request_serializer=ingestion__pb2.ImportDumpRequest.SerializeToString,
                response_deserializer=ingestion__pb2.ImportDumpResponse.FromString,
                _registered_method=True)


class IngestionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TriggerIngestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDataCoverage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportDump(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TriggerIngestion': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerIngestion,
                    request_deserializer=ingestion__pb2.TriggerIngestionRequest.FromString,
                    response_serializer=ingestion__pb2.TriggerIngestionResponse.SerializeToString,
            ),
            'SearchBook': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchBook,
                    request_deserializer=ingestion__pb2.SearchBookRequest.FromString,
                    response_serializer=ingestion__pb2.SearchBookResponse.SerializeToString,
            ),
            'GetDataCoverage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDataCoverage,
                    request_deserializer=ingestion__pb2.GetDataCoverageRequest.FromString,
                    response_serializer=ingestion__pb2.GetDataCoverageResponse.SerializeToString,
            ),
            'ImportDump': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportDump,
                    request_deserializer=ingestion__pb2.ImportDumpRequest.FromString,
                    response_serializer=ingestion__pb2.ImportDumpResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ingestion.v1.IngestionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ingestion.v1.IngestionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IngestionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TriggerIngestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ingestion.v1.IngestionService/TriggerIngestion',
            ingestion__pb2.TriggerIngestionRequest.SerializeToString,
            ingestion__pb2.TriggerIngestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ingestion.v1.IngestionService/SearchBook',
            ingestion__pb2.SearchBookRequest.SerializeToString,
            ingestion__pb2.SearchBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDataCoverage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ingestion.v1.IngestionService/GetDataCoverage',
            ingestion__pb2.GetDataCoverageRequest.SerializeToString,
            ingestion__pb2.GetDataCoverageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportDump(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ingestion.v1.IngestionService/ImportDump',
            ingestion__pb2.ImportDumpRequest.SerializeToString,
            ingestion__pb2.ImportDumpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
